/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.io.File;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Employee;
import model.EmployeeHistory;

/**
 *
 * @author BHAVYA PRAKASH
 */
public class UpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    EmployeeHistory employeeList;
    Employee updateEmployee;
    private ImageIcon imgFinal;
    public UpdateJPanel(EmployeeHistory employeeList) {
        initComponents();
        this.employeeList = employeeList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        txtTeamInfo = new javax.swing.JTextField();
        txtPositionTitle = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        lbTitle = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();
        lbEmployeeId = new javax.swing.JLabel();
        lbAge = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        lbStartDate = new javax.swing.JLabel();
        lbLevel = new javax.swing.JLabel();
        lbTeamInfo = new javax.swing.JLabel();
        lbPositionTitle = new javax.swing.JLabel();
        lbPhoneNumber = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmployeeId = new javax.swing.JTextField();
        btnUploadPhoto = new javax.swing.JButton();
        txtAge = new javax.swing.JTextField();
        cropImageJLabel = new javax.swing.JLabel();
        txtLevel = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        lbEmployeeId1 = new javax.swing.JLabel();
        txtEmployeeIdSearch = new javax.swing.JTextField();
        startDateChooser = new com.toedter.calendar.JDateChooser();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        radioOther = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));

        txtPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyPressed(evt);
            }
        });

        lbTitle.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lbTitle.setText("Edit Employee Profile");

        lbName.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lbName.setText("Name");

        lbEmployeeId.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lbEmployeeId.setText("Employee ID");

        lbAge.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lbAge.setText("Age");

        lbGender.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lbGender.setText("Gender");

        btnUpdate.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnUpdate.setText("Update Changes");
        btnUpdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lbStartDate.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lbStartDate.setText("Start Date");

        lbLevel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lbLevel.setText("Level");

        lbTeamInfo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lbTeamInfo.setText("Team Info");

        lbPositionTitle.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lbPositionTitle.setText("Position Title");

        lbPhoneNumber.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lbPhoneNumber.setText("Phone number");

        lbEmail.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lbEmail.setText("Email ");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });

        btnUploadPhoto.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnUploadPhoto.setText("Upload New Photo");
        btnUploadPhoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUploadPhoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUploadPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadPhotoActionPerformed(evt);
            }
        });

        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
        });

        cropImageJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/profile-icon.jpg"))); // NOI18N

        btnView.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btnView.setText("View");
        btnView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lbEmployeeId1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lbEmployeeId1.setText("Enter employee id to get the profile");

        genderGroup.add(radioMale);
        radioMale.setText("Male");

        genderGroup.add(radioFemale);
        radioFemale.setText("Female");

        genderGroup.add(radioOther);
        radioOther.setText("Other");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbName)
                            .addComponent(lbEmployeeId)
                            .addComponent(lbGender)
                            .addComponent(lbStartDate)
                            .addComponent(lbLevel)
                            .addComponent(lbTeamInfo)
                            .addComponent(lbPositionTitle)
                            .addComponent(lbPhoneNumber)
                            .addComponent(lbEmail)
                            .addComponent(lbAge))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioFemale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioOther))
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnUploadPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(cropImageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(lbTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbEmployeeId1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmployeeIdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {startDateChooser, txtAge, txtEmail, txtEmployeeId, txtLevel, txtName, txtPhoneNumber, txtPositionTitle, txtTeamInfo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmployeeId1)
                    .addComponent(btnView)
                    .addComponent(txtEmployeeIdSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEmployeeId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(radioMale)
                            .addComponent(radioFemale)
                            .addComponent(radioOther)
                            .addComponent(lbGender))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lbStartDate)
                            .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLevel)))
                    .addComponent(cropImageJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTeamInfo)
                    .addComponent(btnUploadPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPositionTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPhoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {startDateChooser, txtAge, txtEmail, txtEmployeeId, txtLevel, txtName, txtPhoneNumber, txtPositionTitle, txtTeamInfo});

    }// </editor-fold>//GEN-END:initComponents
    private boolean validation(String input, String regexPattern){
        Pattern pattern = Pattern.compile(regexPattern,Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(input);
        return matcher.find();
        
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        try{
          String name = txtName.getText();
            if(name.length()==0 || !validation(name,"^(?![\\s.]+$)[a-zA-Z\\s.]*$")){
             JOptionPane.showMessageDialog(this,"Invalid Name");
             return;
            }
            String employeeId = txtEmployeeId.getText();
            if(employeeId.length()==0 || !validation(employeeId,"^(?![\\s.]+$)[a-zA-Z0-9\\s.]*$")){
             JOptionPane.showMessageDialog(this,"Invalid Employee. Can contain only alphabets and numbers");
             return;
            }
            int age = Integer.parseInt(txtAge.getText());
            if(!(age >= 18 && age <= 65)){
             JOptionPane.showMessageDialog(this,"Invalid Age. Age should be between 18 to 65"); 
             return;
            }
            String gender;
            if(radioMale.isSelected()){
                    gender = "Male";
                }
             else if (radioFemale.isSelected()){
                   gender = "Female";
                }
             else if(radioOther.isSelected()){
                    gender = "Other";
                }
             else {
                 gender = "";
             }
             if(gender.length()==0 ){
             JOptionPane.showMessageDialog(this,"Invalid Gender ");
             return;
            }
            Date startDate = startDateChooser.getDate();
             if(startDate==null){
             JOptionPane.showMessageDialog(this,"Invalid Date");
             return;
            }
            String level = txtLevel.getText();
            if(level.length()==0 || !validation(level,"^(?![\\s.]+$)[a-zA-Z0-9\\s.]*$")){
             JOptionPane.showMessageDialog(this,"Invalid Level.Can contain only alphabets and numbers");
             return;
            }
            String teamInfo = txtTeamInfo.getText();
             if(teamInfo.length()==0 || !validation(teamInfo,"^(?![\\s.]+$)[a-zA-Z0-9\\s.]*$")){
             JOptionPane.showMessageDialog(this,"Invalid Team Info.Can contain only alphabets and numbers");
             return;
            }
            String positionTitle = txtPositionTitle.getText();
             if(positionTitle.length()==0 || !validation(positionTitle,"^(?![\\s.]+$)[a-zA-Z0-9\\s.]*$")){
             JOptionPane.showMessageDialog(this,"Invalid Position Title.Can contain only alphabets and numbers");
             return;
            }
            String cellPhoneNumber = txtPhoneNumber.getText();
            
            if(!validation(cellPhoneNumber,"^\\d{10}$")){
             JOptionPane.showMessageDialog(this,"Invalid Phone Number");
             return;
            }
            String email = txtEmail.getText();
            
             if(email.length()==0 || !validation(email,"^(.+)@(\\S+)$")){
             JOptionPane.showMessageDialog(this,"Invalid Email");
             return;
            }
            
            
            if(imgFinal == null){
              JOptionPane.showMessageDialog(this,"Invalid Photo");
             return;  
            }

            updateEmployee.setName(name);
            updateEmployee.setEmployeeId(employeeId);
            updateEmployee.setAge(age);
            updateEmployee.setGender(gender);
            updateEmployee.setStartDate(startDate);
            updateEmployee.setLevel(level);
            updateEmployee.setTeamInfo(teamInfo);
            updateEmployee.setPositionTitle(positionTitle);
            updateEmployee.setCellPhoneNumber(cellPhoneNumber);
            updateEmployee.setEmail(email);
            updateEmployee.setEmployeePhoto(imgFinal);

            JOptionPane.showMessageDialog(this,"Employee Updated.");

            txtName.setText("");
            txtEmployeeId.setText("");
            txtAge.setText("");
            genderGroup.clearSelection();
            startDateChooser.setCalendar(null);
            txtLevel.setText("");
            txtTeamInfo.setText("");
            txtPositionTitle.setText("");
            txtPhoneNumber.setText("");
            txtEmail.setText("");
            cropImageJLabel.setIcon(new ImageIcon(getClass().getResource("/ui/profile-icon.jpg")));
            txtEmployeeIdSearch.setText("");
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Invalid Input. Error updating employee");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnUploadPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadPhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File image=chooser.getSelectedFile();
        String fName=image.getAbsolutePath();
        ImageIcon imgIcon=new ImageIcon(fName);
        if(fName.toLowerCase().endsWith(".jpg") || fName.toLowerCase().endsWith(".jpeg")){
        Image img=imgIcon.getImage();
        Image pic=img.getScaledInstance(cropImageJLabel.getWidth(), cropImageJLabel.getHeight(), SCALE_SMOOTH);
        imgFinal=new ImageIcon(pic);
        //picTxtFld.setText(fName);
        //request.setImgIcon(imgFinal);
        cropImageJLabel.setIcon(imgFinal);
        }
        else{
             JOptionPane.showMessageDialog(this, "Invalid File. Upload a jpeg/jpg file");   
            }
    }//GEN-LAST:event_btnUploadPhotoActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        String employeeId = txtEmployeeIdSearch.getText();
        int i=0;
        for (Employee em : employeeList.getEmployeeList()){

            if( em.getEmployeeId().equalsIgnoreCase(employeeId)){
                txtName.setText(em.getName());
                txtEmployeeId.setText(em.getEmployeeId());
                txtAge.setText(String.valueOf(em.getAge()));
                if("Male".equals(em.getGender())){
                    radioMale.setSelected(true);
                }
                else if ("Female".equals(em.getGender())){
                    radioFemale.setSelected(true);
                }
                else if ("Other".equals(em.getGender())){
                    radioOther.setSelected(true);
                }
                
                startDateChooser.setDate(em.getStartDate());
                txtLevel.setText(String.valueOf(em.getLevel()));
                txtTeamInfo.setText(em.getTeamInfo());
                txtPositionTitle.setText(em.getPositionTitle());
                txtPhoneNumber.setText(String.valueOf(em.getCellPhoneNumber()));
                txtEmail.setText(em.getEmail());
                cropImageJLabel.setIcon(em.getEmployeePhoto());
                i=1;
                updateEmployee = em;
                imgFinal=updateEmployee.getEmployeePhoto();
                break;

            }

        }

        if(i==0){
            JOptionPane.showMessageDialog(this,"No results Found");
            txtName.setText("");
            txtEmployeeId.setText("");
            txtAge.setText("");
            genderGroup.clearSelection();
            startDateChooser.setCalendar(null);
            txtLevel.setText("");
            txtTeamInfo.setText("");
            txtPositionTitle.setText("");
            txtPhoneNumber.setText("");
            txtEmail.setText("");
            cropImageJLabel.setIcon(new ImageIcon(getClass().getResource("/ui/profile-icon.jpg")));
            txtEmployeeIdSearch.setText("");

        }
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)){
            txtName.setEditable(false);
        }
        else{
            txtName.setEditable(true);
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            txtAge.setEditable(false);
        }
        else{
            txtAge.setEditable(true);
        }
    }//GEN-LAST:event_txtAgeKeyPressed

    private void txtPhoneNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)){
            txtPhoneNumber.setEditable(false);
        }
        else{
            txtPhoneNumber.setEditable(true);
        }
    }//GEN-LAST:event_txtPhoneNumberKeyPressed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUploadPhoto;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel cropImageJLabel;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel lbAge;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmployeeId;
    private javax.swing.JLabel lbEmployeeId1;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbLevel;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPhoneNumber;
    private javax.swing.JLabel lbPositionTitle;
    private javax.swing.JLabel lbStartDate;
    private javax.swing.JLabel lbTeamInfo;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    private javax.swing.JRadioButton radioOther;
    private com.toedter.calendar.JDateChooser startDateChooser;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeId;
    private javax.swing.JTextField txtEmployeeIdSearch;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtPositionTitle;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables
}
