/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Employee;
import model.EmployeeHistory;

/**
 *
 * @author BHAVYA PRAKASH
 */
public class ViewFullProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFullProfileJPanel
     */
    EmployeeHistory employeeList;
    public ViewFullProfileJPanel(EmployeeHistory employeeList) {
        initComponents();
        this.employeeList = employeeList;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        lbEmployeeId = new javax.swing.JLabel();
        lbAge = new javax.swing.JLabel();
        lbGender = new javax.swing.JLabel();
        lbStartDate = new javax.swing.JLabel();
        lbLevel = new javax.swing.JLabel();
        lbTeamInfo = new javax.swing.JLabel();
        lbPositionTitle = new javax.swing.JLabel();
        lbPhoneNumber = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        cropImageJLabel = new javax.swing.JLabel();
        lbNameField = new javax.swing.JLabel();
        lbEmployeeIdField = new javax.swing.JLabel();
        lbAgeField = new javax.swing.JLabel();
        lbGenderField = new javax.swing.JLabel();
        lbStartDateField = new javax.swing.JLabel();
        lbLevelField = new javax.swing.JLabel();
        lbTeamInfoField = new javax.swing.JLabel();
        lbPositionTitleField = new javax.swing.JLabel();
        lbPhoneNumberField = new javax.swing.JLabel();
        lbEmailField = new javax.swing.JLabel();
        lbEmployeeId1 = new javax.swing.JLabel();
        txtEmployeeId = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();

        lbName.setText("Name");

        lbEmployeeId.setText("Employee ID");

        lbAge.setText("Age");

        lbGender.setText("Gender");

        lbStartDate.setText("Start Date");

        lbLevel.setText("Level");

        lbTeamInfo.setText("Team Info");

        lbPositionTitle.setText("Position Title");

        lbPhoneNumber.setText("Phone number");

        lbEmail.setText("Email ");

        lbNameField.setText("1");

        lbEmployeeIdField.setText("2");

        lbAgeField.setText("3");

        lbGenderField.setText("4");

        lbStartDateField.setText("5");

        lbLevelField.setText("6");

        lbTeamInfoField.setText("7");

        lbPositionTitleField.setText("8");

        lbPhoneNumberField.setText("9");

        lbEmailField.setText("10");

        lbEmployeeId1.setText("Employee ID");

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEmployeeId)
                                    .addComponent(lbAge)
                                    .addComponent(lbGender)
                                    .addComponent(lbStartDate)
                                    .addComponent(lbLevel)
                                    .addComponent(lbTeamInfo)
                                    .addComponent(lbPositionTitle)
                                    .addComponent(lbPhoneNumber))
                                .addGap(135, 135, 135)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbPhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPositionTitleField, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(lbTeamInfoField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbLevelField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbStartDateField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbGenderField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbAgeField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbEmployeeIdField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(cropImageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbEmail)
                        .addGap(182, 182, 182)
                        .addComponent(lbEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbEmployeeId1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbEmployeeId1)
                                    .addComponent(txtEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnView))
                                .addGap(25, 25, 25)
                                .addComponent(lbName)
                                .addGap(18, 18, 18)
                                .addComponent(lbEmployeeId)
                                .addGap(6, 6, 6)
                                .addComponent(lbAge)
                                .addGap(6, 6, 6)
                                .addComponent(lbGender))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(cropImageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbStartDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLevel)
                        .addGap(12, 12, 12)
                        .addComponent(lbTeamInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbPositionTitle)
                        .addGap(18, 18, 18)
                        .addComponent(lbPhoneNumber)
                        .addGap(18, 18, 18)
                        .addComponent(lbEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lbNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbEmployeeIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbGenderField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(lbStartDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLevelField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTeamInfoField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPositionTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbPhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        String employeeId = txtEmployeeId.getText();
        int i=0;
        for (Employee em : employeeList.getEmployeeList()){
           
            if( em.getEmployeeId().equals(employeeId)){
               lbNameField.setText(em.getName());
               lbEmployeeIdField.setText(em.getEmployeeId());
               lbAgeField.setText(String.valueOf(em.getAge()));
               lbGenderField.setText(em.getGender());
               lbStartDateField.setText(em.getStartDate());
               lbLevelField.setText(String.valueOf(em.getLevel()));
               lbTeamInfoField.setText(em.getTeamInfo());
               lbPositionTitleField.setText(em.getPositionTitle());
               lbPhoneNumberField.setText(String.valueOf(em.getCellPhoneNumber()));
               lbEmailField.setText(em.getEmail());
               cropImageJLabel.setIcon(em.getEmployeePhoto());
                i=1;
                break;
                
                      
            }
            
        }
        
        if(i==0){
                JOptionPane.showMessageDialog(this,"No results Found");
              
            }
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.JLabel cropImageJLabel;
    private javax.swing.JLabel lbAge;
    private javax.swing.JLabel lbAgeField;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmailField;
    private javax.swing.JLabel lbEmployeeId;
    private javax.swing.JLabel lbEmployeeId1;
    private javax.swing.JLabel lbEmployeeIdField;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbGenderField;
    private javax.swing.JLabel lbLevel;
    private javax.swing.JLabel lbLevelField;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbNameField;
    private javax.swing.JLabel lbPhoneNumber;
    private javax.swing.JLabel lbPhoneNumberField;
    private javax.swing.JLabel lbPositionTitle;
    private javax.swing.JLabel lbPositionTitleField;
    private javax.swing.JLabel lbStartDate;
    private javax.swing.JLabel lbStartDateField;
    private javax.swing.JLabel lbTeamInfo;
    private javax.swing.JLabel lbTeamInfoField;
    private javax.swing.JTextField txtEmployeeId;
    // End of variables declaration//GEN-END:variables
}
